# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mypaceshun/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: autopep8
    -   id: autoflake
    -   id: isort
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.6.0
    hooks:
    -   id: eslint
        verbose: true
        args: ["--fix"]
        additional_dependencies:
          - eslint@8.6.0
          - eslint-config-google@0.14.0
