member_list = {"class": [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3],
               "name": ["sarina_ushio", "yuka_kageyama", "shiho_kato",
                        "kyoko_saito", "kumi_sasaki", "mirei_sasaki",
                        "mana_takase", "ayaka_takamoto", "mei_higashimura",
                        "miku_kanemura", "hina_kawata", "nao_kosaka",
                        "suzuka_tomita", "akari_nibu", "hiyori_hamagishi",
                        "konoka_matsuda", "manamo_miyata", "miho_watanabe",
                        "hinano_kamimura", "mikuni_takahashi", "mari_morimoto",
                        "haruyo_yamaguti"],
               "ja_name": ["潮 紗理菜", "影山 優佳", "加藤 志帆",
                           "斎藤 京子", "佐々木 久美", "佐々木 美玲",
                           "高瀬 愛奈", "高本 彩花", "東村 芽衣",
                           "金村 美玖", "河田 陽菜", "小坂 菜緒",
                           "富田 鈴花", "丹生 明里", "濱岸 ひより",
                           "松田 好花", "宮田 愛萌", "渡邉 美穂",
                           "上村 ひなの", "高橋 未来虹", "森本 茉莉",
                           "山口 陽世"]}
